Projeto_Erik_Abdala/config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *
from app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = 'index.html'), name = 'index'),
    path('area/', area, name = 'areas'),
    path('fisico/', fisico, name = 'fisicos'),
    path('invencao/', invencao, name = 'invencoes'),
    path('subarea/', subarea, name = 'subareas'),
    path('pessoa/', pessoa, name = 'pessoa'),

    path("topico/", TopicoListView.as_view(), name = 'topicoList'),
    path("topico/<int:pk>/", TopicoDetailView.as_view(), name = 'topicoDetail'),

    path("questionario/", QuestionarioListView.as_view(), name = 'questionarioList'),
    path("questionario/<int:pk>/", QuestionarioDetailView.as_view(), name = 'questionarioDetail'),

    path("submeter_respostas/<int:questionario_id>/", views.submeter_respostas, name = 'submeter_respostas'),

    path('respondido/', respondido, name = 'respondidos'),

]

Projeto_Erik_Abdala/app/models.py
from django.db import models

# Create your models here.

class Area(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)

    def __str__(self):

        return f'{self.nome}'
    
class Subarea(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    area = models.ForeignKey(Area, on_delete = models.CASCADE)

    def __str__(self):

        return f'Subárea: {self.nome} Área: {self.area}'
    
class Topico(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 500)
    subarea = models.ForeignKey(Subarea, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.nome} {self.descricao} {self.subarea}'
    
class Fisico(models.Model):

    nome = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    data_nascimento = models.DateField()

    def __str__(self):

        return f'{self.nome} {self.descricao} {self.data_nascimento}'
    
class Invencao(models.Model):

    nome = models.CharField(max_length = 80)
    ano = models.DateField()
    fisico = models.ManyToManyField(Fisico)
    area = models.ManyToManyField(Area)

    def __str__(self):

        return f'{self.nome} {self.ano} {self.fisico} {self.area}'
    
class Questionario(models.Model):

    titulo = models.CharField(max_length = 80)
    descricao = models.CharField(max_length = 300)
    area = models.ForeignKey(Area, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.titulo} {self.descricao} {self.area}'
    
class Questao(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE)
    titulo = models.CharField(max_length = 80)
    enunciado = models.CharField(max_length = 500)
    alternativa_a = models.CharField(max_length = 300)
    alternativa_b = models.CharField(max_length = 300)
    alternativa_c = models.CharField(max_length = 300)
    alternativa_d = models.CharField(max_length = 300)
    alternativa_e = models.CharField(max_length = 300)
    alternativa_correta = models.CharField(max_length = 1)
    alternativa_submetida = models.CharField(max_length = 1, blank = True, null = True)

    def __str__(self):

        return f'{self.titulo} {self.enunciado} {self.alternativa_a}' \
        f'{self.alternativa_b} {self.alternativa_c} {self.alternativa_d}' \
        f'{self.alternativa_e} {self.alternativa_correta}' \
        f'{self.alternativa_submetida}'
    
class Ocupacao(models.Model):

    nome = models.CharField(max_length = 30)

    def __str__(self):

        return self.nome
    
class Pessoa(models.Model):

    nome = models.CharField(max_length = 80)
    email = models.CharField(max_length = 50)
    ocupacao = models.ForeignKey(Ocupacao, on_delete = models.CASCADE)

    def __str__(self):

        return f'{self.nome} {self.email} {self.ocupacao}'
    
class QuestionarioRespondido(models.Model):

    questionario = models.ForeignKey(Questionario, on_delete = models.CASCADE)
    pessoa = models.ForeignKey(Pessoa, on_delete = models.CASCADE)
    data_realizacao = models.DateTimeField()
    numero_acertos = models.PositiveIntegerField()
    respostas_usuario = models.TextField(blank=True, null=True)

    def __str__(self):

        return f'{self.questionario} {self.pessoa} {self.data_realizacao} {self.numero_acertos} {self.respostas_usuario}'

Projeto_Erik_Abdala/app/templates/exibicao/questionario/questionario-detail.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionario">Questionários</a>
          <a href="/respondido">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>

  {{ membros }}
  
  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Questionários</h2>
    <h4>{{ questionario.id }} | {{ questionario.titulo }} | {{ questionario.area }}</h4><br>
    {% for Questao in questionario.questao_set.all %}
    <form name = "Formulario" method = "post" action = "{% url 'submeter_respostas' questionario.id %}">{% csrf_token %}
        <h5>{{ Questao.id }} - {{ Questao.titulo }}</h5><br>
        <p style="font-weight: normal;">{{ Questao.enunciado}}</p>
        <input type = 'radio' placeholder = "Questão 1-A" name = "Q{{ Questao.id }}" value = "A">
        <label for = "Q{{ Questao.id }}A">{{ Questao.alternativa_a }}</label><br>
        <input type = 'radio' placeholder = "Questão 1-B" name = "Q{{ Questao.id }}" value = "B">
        <label for = "Q{{ Questao.id }}B">{{ Questao.alternativa_b }}</label><br>
        <input type = 'radio' placeholder = "Questão 1-C" name = "Q{{ Questao.id }}" value = "C">
        <label for = "Q{{ Questao.id }}C">{{ Questao.alternativa_c }}</label><br>
        <input type = 'radio' placeholder = "Questão 1-D" name = "Q{{ Questao.id }}" value = "D">
        <label for = "Q{{ Questao.id }}D">{{ Questao.alternativa_d }}</label><br>
        <input type = 'radio' placeholder = "Questão 1-E" name = "Q{{ Questao.id }}" value = "E">
        <label for = "Q{{ Questao.id }}E">{{ Questao.alternativa_e }}</label><br>
    {% endfor %}
        <div class = "form-group">
            <label for = "membro">Pessoa:</label>
            <select class = "form-control" id="membro" name = "membro">
            {% for Pessoa in membros %}
                <option value="{{ Pessoa.id }}">{{ Pessoa.nome }}</option>
            {% endfor %}
            </select>
        </div>
    <input type = "submit" value = "Enviar">
    </form>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Projeto_Erik_Abdala/app/templates/exibicao/questionario/questionario-list.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>IFisica</title>
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a href="/"><img src="{% static 'img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-right: 8px;"></a>
    <a class="navbar-brand" href="/">IFisica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link text-dark" href="/">Home</a>
          </li>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Áreas<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/area">Áreas</a>
          <a href = "/subarea">Subáreas</a>
          <a href = "/topico">Tópicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Invenções<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href = "/invencao">Invenções</a>
          <a href = "/fisico">Físicos</a>
        </div>
        </div>
        <div class = "dropdown">
        <button class = "nav-link text-dark dropbtn">Questionários<i class = "arrow down"></i></button>
        <div class = "dropdown-content">
          <a href="/questionario">Questionários</a>
          <a href="/respondido">Envios</a>
        </div>
        </div>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/pessoa">Integrantes</a>
        </li>
        <li id = "adm" class="nav-item">
          <a class="nav-link text-dark" href="/admin/">Administração</a>
        </li>
      </ul>
    </div>
  </nav>
  
  <div class="container mt-5">
    <h2 style = "text-align: center;" class="mb-4">Questionários</h2>
    <ul class = "teste3-1">
        {% for Questionario in questionarios %}
        <li class = "teste3-2">{{ Questionario.id }} - <a href="{% url 'questionarioDetail' Questionario.pk %}">{{ Questionario.titulo }}</a></li>
        {% endfor %}
    </ul>
  </div>

  <!-- Incluindo jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>